spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:duder # /h2-console 에서 이 주소로 들어가면 됨
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 만들기 전에 테이블 있으면 삭제
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug