spring:
  profiles:
    active: local
    include: oauth

  jackson: # jackson 기본전략은 Lower_Camel_Case
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:duder # /h2-console 에서 이 주소로 들어가면 됨
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/duder?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rla123

  jpa:
    hibernate:
      ddl-auto: validate # 만들기 전에 테이블 있으면 삭제
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug